
songs:
   default:
       name: Tujhe Dekha to ye jaana sanam.
       rating : 5
       lyrics: Tujhe Dekha to ye jaana sanam . Pyaar Hota h deewana sanam . Ab yha se kha jaaen hum . Teri baahon me mar jaeen hum .
 
---

   
loggin:
  level:
    com.katariasoft : trace
  path: ${user.home}/logs/applications/${spring.application.name}
  file: ${logging.path}/${spring.application.name}.log  
  patter:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %line %msg%n"   
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger - %line %msg%n"

     


      
     
          
           
    


        