spring:
  application:
    name: movie-service
  profiles:
    active: dev

---
#Defining a logging.level for any package creates a logger for this package . This logger will
#not have any appender . Hence appneder of root logger will be used . Secondly this logger will
#filter logs on this defined level . If this logger has logging level as trace hence all the log
#messages will go to root logger and root logger even if having level as info will pring this log
#as filters will not be executed on parent loggers .       
#
#Path will define the path where logging needs to be configured.
#File will be file name .

#pattern defined for console and file will override defult spring patterns . 
# In Prod generally console appender is not needed hence define it as empty . 

#
#


spring:
   profiles: dev   
loggin:
  level:
    com.katariasoft : trace
  path: ${user.home}/logs/applications/${spring.application.name}
  file: ${logging.path}/${spring.application.name}.log  
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"   
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    
    
---
# Below config is for prod profile which means no console appender will be created . 
# To have daily rolling polity use logback-spring.xml     
    
spring:
   profiles: prod   
loggin:
  level:
    com.katariasoft : trace
  path: ${user.home}/logs/applications/${spring.application.name}
  file: ${logging.path}/${spring.application.name}.log  
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"   
    console: 
  
     
---
server:
    port : 8100
   
   
---
movie : 
    default :
         id: -1
         name: Dil Wale Dulhania Le jaenge
         actor: shahrukh khan
         actress : Kajol
         releaseDate: 01-Jan-2000
         budget: 50Cr
         grossIncome: 400cr
         verdict: Super Duper Hit
         starRating: 10 
         

---
movie: 
   art: 
      default: 
            id: -1
            name: Kamasutra
            actor: Kamdev
            actress: Kajol
            releaseDate: 01-Jan-2018
            budget: 50Cr
            grossIncome: 400cr
            verdict: Super Duper Hit
            starRating: 10 
---

movie: 
   adult: 
      default: 
            id: -3
            name: American Canadian pie
            actor: Ironmanne
            actress: IronWoman
            releaseDate: 01-Jan-2018
            budget: 50Cr
            grossIncome: 400cr
            verdict: Super Duper Hit
            starRating: 10 

---

user: 
    goodName: Sahil from default profile 11
    clazz: 10th
    subjects: 
              - Hindi
              - Eng
              - Maths
              - Science
              - SST
              - GEO
              - GEO1
              - GEO2
    projects:
               project1: PRJ302
               project2: PRJ303
               project3: PRJ304
               project4: PRJ305
               project5: PRJ306
               project6: PRJ307
    credentials:
               userName: userName
               passWord: password
    address:   Main Street USA
    favourite:
               super-hero: ironman
               music_director: Downey Jr.
               apperalBrand: Flying Machine
    favouriteMap:
               old:
                  super-hero: superman
                  music_director: David
                  apperalBrand: Pepe
               new:
                  super-hero: ironman
                  music_director: Downey Jr.
                  apperalBrand: Flying Machine
    
    contacts:
             - number: 8742910240
               mail:  vaneet.kumar@yatra.com
             - number:  8742910241
               mail:  vaneet1.kumar@yatra.com
  
--- 

redis:
              host : 189.90.89.70 From application.yml profile
              port : 7890
              password: vaneet
              
               
---

    spring:
      profiles: prod
    redis:
              host : 189.90.89.70 From prod profile
              port : 7890
              password: vaneet
---              
              
    spring:
      profiles: dev
    redis:
              host : 189.90.89.70 From dev profile 1
              port : 7890
              password: vaneet
---  


    
   


        
                 
              

              
    
       
    



















 