
server:
    port : 8100
   
   
---
movie : 
    default :
         id : 0
         name: Dil Wale Dulhania Le jaenge
         actor: shahrukh khan
         actress : Kajol
         releaseDate: 01-Jan-2000
         budget: 50Cr
         grossIncome: 400cr
         verdict: Super Duper Hit
         starRating: 45

---
movie: 
   art: 
      default: 
            id: -1
            name: Kamasutra
            actor: Kamdev
            actress: Kajol
            releaseDate: 01-Jan-2018
            budget: 50Cr
            grossIncome: 400cr
            verdict: Super Duper Hit
            starRating: 10 


















 